
--a list of all events that can arrive, for conveniennce
return {"clock","ready",
"serverLoaded","serverCommandPoolUpdate",
"serverSaveConfig",
"shardReady","onBotLocalSync",
"onBotReady","onBotLocalSave",
"shardResumed","channelCreate",
"channelUpdate","channelDelete",
"recipientAdd","recipientRemove",
"guildAvailable","guildCreate",
"guildUpdate","guildUnavailable",
"guildDelete","userBan",
"userUnban","emojisUpdate",
"memberJoin","memberLeave",
"memberUpdate","roleCreate",
"roleUpdate","roleDelete",
"messageCreate","messageUpdate",
"messageUpdateUncached","messageDelete",
"messageDeleteUncached","reactionAdd",
"reactionAddUncached","reactionRemove",
"reactionRemoveUncached","pinsUpdate",
"presenceUpdate","relationshipUpdate",
"relationshipAdd","relationshipRemove",
"typingStart","userUpdate",
"voiceConnect","voiceDisconnect",
"voiceUpdate","voiceChannelJoin",
"voiceChannelLeave","webhooksUpdate","debug",
"info","error","heartbeat","raw"}

